CREATE DATABASE IF NOT EXISTS superblox;

CREATE TABLE `assets` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `info` TEXT NOT NULL,
  `creatorid` INT NOT NULL,
  `playing` INT NOT NULL DEFAULT 0,
  `maxplayer` INT NOT NULL,
  `favorited` INT NOT NULL DEFAULT 0,
  `version` VARCHAR(20) NOT NULL,
  `createdon` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `assetype` VARCHAR(50) NOT NULL,
  `genre` VARCHAR(100),
  `approved` BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `users` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `rank` VARCHAR(50) NOT NULL,
  `message` TEXT DEFAULT NULL,
  `robux` INT NOT NULL DEFAULT 0,
  `tix` INT NOT NULL DEFAULT 0,
  `blurb` VARCHAR(255) DEFAULT '',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `token` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
